bot:
    prefix:         "+"
    token:          "token"
    description:    "Self-built multi-use discord bot"

    status:         "adal esta menso"

    presence:
        jugando:    "ola toy jugando"

style: 
    colours: 
        blue:           0x3775a8
        bright_green:   0x01d277
        orange:         0xe67e22
        pink:           0xcf84e0
        purple:         0xb734eb
        soft_green:     0x68c290
        soft_orange:    0xf9cb54
        soft_red:       0xcd6d6d
        white:          0xfffffe
        yellow:         0xffd241
    
    emojis:
        # static
        agucatatito:                            '<:agucatatito:1080334428053704855>'
        pixel_number_one:                       '<:pixel_number_one:1081267770387349504>'
        pixel_number_two:                       '<:pixel_number_two:1081267766029463644>'
        pixel_number_three:                     '<:pixel_number_three:1081267764804734986>'
        pixel_number_four:                      '<:pixel_number_four:1081267768483135558>'
        pixel_number_five:                      '<:pixel_number_five:1081267767426166885>'
        pixel_number_six:                       '<:pixel_number_six:1081267763546427563>'
        pixel_number_seven:                     '<:pixel_number_seven:1081267771863728318>'
        goldstar:                               '<:goldstar:1081062638118780938>'
        villager_what:                          '<:Villager_Question_What:1081062632200618094>'
        lock:                                   '<:lock:1081062628744507442>'
        kheverga:                               '<:kheverga:1081062627448471572>'
        info:                                   '<:info:1081062625414234143>'
        overwatch:      &OVERWATCH_EMOJI        '<:overwatch:1081062521718439988>'
        rocket_league:  &ROCKET_LEAGUE_EMOJI    '<:rocket_league:1085740047212482590>' 

        # animated
        green_check_mark:               '<:GreenCheckMark:1081062523882705069>'
        black_and_white_tick:           '<:black_and_white_tick:1081062636717867059>'
        agent_warning:                  '<:AGENT_Warning:1081062634419388467>'
        warning:                        '<:Warning:1081062633337274388>'
        tick_red:                       '<:tick_red:1081062630380294185>'

        game_emojis:
            - *OVERWATCH_EMOJI
            - *ROCKET_LEAGUE_EMOJI
        game_names:
            - 'overwatch'
            - 'rocket_league'

guild:
    id:     1078937524522717234
    name:   "Gaming Championship Series"
    invite: "https://discord.gg/hxEu928qM3"

    categories:
        # various general categories
        stats:          1078937525499985984
        admin:          1078937525281886258
        lobby:          1078937524564656209
        info:           1078937524564656211
        text:           1078937525026041869
        voice:          1078937525026041872

        # game categories
        overwatch:      1080514923450351757
    
    channels:
        # public announcements and news channels
        rules:          1078937524564656212
        welcome:        1078937524564656210
        announcements:  1078937525026041866
        tourney:        1080280196986437672

        # looking for team
        LFT:            1080899228169154700

        # support / help
        support:        1078937525281886256
    
    roles:

        # server team
        leader:     &CUCHAO_ROLE        1078937524564656208
        staff:      &ADMINS_ROLE        1078937524522717242
        developer:  &DEVS_ROLE          1078937524522717243
        mod:        &MODERATORS_ROLE    1078937524522717241

        # content creation
        editor:             1078937524522717240
        content_creator:    1078937524522717237
        caster:             1080584215097258045
        tester:             1078937524522717238

        # bots
        pepe:               1080283720705130509
        bots:               1078937524522717239

        # player type
        contender:          1080581645528203274
        player:             1078937524522717236

        # games
        overwatch:      &OVERWATCH_ROLE         1085738041504706571
        rocket_league:  &ROCKET_LEAGUE_ROLE     1085739389801463959
    
    moderation_roles:
        - *CUCHAO_ROLE
        - *ADMINS_ROLE
        - *DEVS_ROLE
        - *MODERATORS_ROLE

    game_roles:
        - *OVERWATCH_ROLE
        - *ROCKET_LEAGUE_ROLE
