bot:
    prefix:         "+"
    token:          "token"
    description:    "Self-built multi-use discord bot"

style: 
    colours: 
        blue:           0x3775a8
        bright_green:   0x01d277
        orange:         0xe67e22
        pink:           0xcf84e0
        purple:         0xb734eb
        soft_green:     0x68c290
        soft_orange:    0xf9cb54
        soft_red:       0xcd6d6d
        white:          0xfffffe
        yellow:         0xffd241
    
    emojis:
        agucatatito:    1080989017031585872
    
guild:
    id:     1078937524522717234
    name:   "Gaming Championship Series"
    invite: "https://discord.gg/hxEu928qM3"

    categories:
        # various general categories
        stats:      1078937525499985984
        admin:      1078937525281886258
        lobby:      1078937524564656209
        info:       1078937524564656211
        text:       1078937525026041869
        voice:      1078937525026041872

        # game categories
        overwatch:         1080514923450351757
    
    channels:
        # public announcements and news channels
        rules:          1078937524564656212
        welcome:        1078937524564656210
        announcements:  1078937525026041866
        tourney:        1080280196986437672

        # looking for team
        LFT:        1080899228169154700

        # support / help
        support:    1078937525281886256
    
    roles:

        # server team
        leader:     &CUCHAO_ROLE        1078937524564656208
        staff:      &ADMINS_ROLE        1078937524522717242
        developer:  &DEVS_ROLE          1078937524522717243
        mod:        &MODERATORS_ROLE    1078937524522717241

        # content creation
        editor:             1078937524522717240
        content-creator:    1078937524522717237
        caster:             1080584215097258045
        tester:             1078937524522717238

        # bots
        pepe:               1080283720705130509
        bots:               1078937524522717239

        # player type
        contender:          1080581645528203274
        player:             1078937524522717236

        # games
        overwatch :         1080283720705130509
    
    moderation_roles:
        - *CUCHAO_ROLE
        - *ADMINS_ROLE
        - *DEVS_ROLE
        - *MODERATORS_ROLE

